language: php

php:
  - 5.3
  - 5.4
  - 5.5

env:
  global:
    - PLUGIN_NAME=PredictionIO
    - REQUIRE=""
    - DB=mysql CAKE_VERSION=2.4

  matrix:
    - DB=mysql CAKE_VERSION=2.2
    - DB=mysql CAKE_VERSION=2.3
    - DB=mysql CAKE_VERSION=2.4
    - DB=mysql CAKE_VERSION=2.5
    - DB=mysql CAKE_VERSION=master

matrix:
  include:
    - php: 5.4
      env:
        - COVERALLS=1
    - php: 5.4
      env:
        - PHPCS=1
  allow_failures:
    - env: DB=mysql CAKE_VERSION=2.5

before_script:
  - git clone https://github.com/FriendsOfCake/travis.git --depth 1 ../travis
  - ../travis/before_script.sh
  - echo "CakePlugin::loadAll(array('$PLUGIN_NAME' => array('bootstrap' => true)));" >> ../cakephp/app/Config/bootstrap.php
  - echo "<?xml version=\"1.0\" encoding=\"UTF-8\"?>
    <phpunit colors=\"true\">
        <filter>
            <whitelist addUncoveredFilesFromWhitelist=\"true\">
                <directory suffix=\".php\">Plugin/$PLUGIN_NAME</directory>
                <exclude>
                    <directory suffix=\".php\">Plugin/$PLUGIN_NAME/vendor</directory>
                    <directory suffix=\".php\">Plugin/$PLUGIN_NAME/Test</directory>
                    <directory suffix=\".php\">Plugin/$PLUGIN_NAME/Config</directory>
                </exclude>
            </whitelist>
        </filter>
    </phpunit>" > phpunit.xml

script:
  - ../travis/script.sh

after_success:
  - ../travis/after_success.sh
