language: php

php:
  - 5.3
  - 5.4
  - 5.5

env:
  global:
    - PLUGIN_NAME=PredictionIO
    - REQUIRE=""
    - DB=mysql CAKE_VERSION=2.4

  matrix:
    - DB=mysql CAKE_VERSION=2.2
    - DB=mysql CAKE_VERSION=2.3
    - DB=mysql CAKE_VERSION=2.4
    - DB=mysql CAKE_VERSION=2.5

matrix:
  include:
    - php: 5.4
      env:
        - COVERALLS=1
    - php: 5.4
      env:
        - PHPCS=1
    - php: 5.4
      env:
        - FOC_VALIDATE=1
  allow_failures:
    - env: CAKE_VERSION=2.5

before_script:
  - git clone https://github.com/FriendsOfCake/travis.git --depth 1 ../travis
  - ../travis/before_script.sh

script:
  - ../travis/script.sh

after_success:
  - ../travis/after_success.sh
